FROM registry.htbsvc.net/hackthebox/htb:coding_template

COPY --chown=root challenge/challenge.py /root/checker
COPY --chown=root challenge/flag.txt /root/checker
COPY --chown=root challenge/story.txt /root/checker
COPY --chown=www-data challenge/index.html /app/templates
